config/routes.rb
Rails.application.routes.draw do

  get 'set/index'

  get 'set/new/createTour'

  get 'management/index'

  get 'courier_location/index'

  get 'monitor/index'

  get 'courier/index'

namespace :v1 do
	resources :routes
	resources :sessions, only: [:create, :destroy]
	resources :locations
end

devise_for :users

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

get 'genetic_algorithm/index'

root to: 'home#index'

resources :places
get 'home/index'
get 'home/createTour'

get "home/new"
get "homefetch/:job_id", controller: :home, action: :fetch
post "home/create"

match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :user
end

app/models/place.rb
class Place < ApplicationRecord
	
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_token_authenticatable
	
	has_many :locations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/way.rb
class Way < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :null_session
  acts_as_token_authentication_handler_for User, fallback: :none
end

app/controllers/home_controller.rb
 class HomeController < ApplicationController
  before_action :authenticate_user!
 	def index
  		
	end

  def create
    @job_id = HardWorker.perform_async(my_params.to_json)
    render :status => :accepted, :json => { jobId: @job_id }
  end
  
  def fetch
    job_id = my_params_job['id']

    if Sidekiq::Status::complete? job_id
      render :plain => Sidekiq::Status::get(job_id, :solution), :status => 200
      @solution_array = Sidekiq::Status::get(job_id, :solution_array)
      $array_cities = ActiveSupport::JSON.decode(@solution_array)
      #@array_cities.each do |i| 
      #  Route.create(city: i, user_id: current_user.id)
      #end

    elsif Sidekiq::Status::failed? job_id
      render :plain => 'Failed', :status => 500
    else
      render :plain => '', :status => 202
    end
  end
# nie uzywame createTour !!!!
  def createTour
    userId = params[:user_id]

    $array_cities.each do |i|
        Route.create(city: i, userId: user_id)
    end
    flash[:notice] = "Route was saved successfully!!!"
    #redirect_to(:action=>'index', :kategoria_id => @kategorie.id)
    render :plain => 'Saved', :status => 200

  end
  
  protected
    def my_params
      params.permit(:cities => [], :distances => [:origin, :destination, :distance])
    end

    def my_params_job
      params.permit(:id)
    end

    def place_params
      params.permit(:city, :user_id)
    end

    def params_user_id
      params.permit(:user_id)
    end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  def index
  	@users = User.all;
  end
end

app/controllers/monitor_controller.rb
class MonitorController < ApplicationController
  def index
  	@users = User.all;
  end

  def view
  	@user_id = params[:id]
  	@user_to_monit = User.find(@user_id)
  	@position_gps = Location.where(:user_id => @user_id)
  	@users_current_route = Route.where(:user_id => @user_id)
  	
  end

  def params_user_id
      params.permit(:id)
  end

end

app/controllers/set_controller.rb
class SetController < ApplicationController
  before_action :authenticate_user!
  def index
  	@users = User.all;
  end

  def new

  end

  def create
    @job_id = HardWorker.perform_async(my_params.to_json)
    render :status => :accepted, :json => { jobId: @job_id }
  end
 
  def fetch
    job_id = my_params_job['id']

    if Sidekiq::Status::complete? job_id
      render :plain => Sidekiq::Status::get(job_id, :solution), :status => 200
      @solution_array = Sidekiq::Status::get(job_id, :solution_array)
      $array_cities = ActiveSupport::JSON.decode(@solution_array)
    elsif Sidekiq::Status::failed? job_id
      render :plain => 'Failed', :status => 500
    else
      render :plain => '', :status => 202
    end
  end
  
  def createTour

	id = params[:id]
    $array_cities.each do |i|
        Route.create(city: i, user_id: id)
    end
    flash[:notice] = "Route was saved successfully!!!"
    redirect_to(:controller => 'home', :action => 'index')
    #render :plain => 'Saved', :status => 200
  end

   protected
    def my_params
      params.permit(:cities => [], :distances => [:origin, :destination, :distance])
    end

    def my_params_job
      params.permit(:id)
    end

    def params_user_id
      params.permit(:id)
    end

end

app/controllers/v1/locations_controller.rb
class V1::LocationsController < ApplicationController
  before_action :authenticate_user!
  
	def index
		@locations = Location.all
		
		render json: @locations, status: :ok
	end

	def create
    
    @location = Location.new(location_params)
    @location.user = current_user

    if @location.save
      render json: @location, status: :ok
    else
      head(:unauthorized)
    end

  end

  def location_params
      params.permit(:longitude, :latitude)
  end
end

app/controllers/v1/routes_controller.rb
class V1::RoutesController < ApplicationController
  before_action :authenticate_user!
  
	def index
		@routes = Route.where(:user_id => current_user.id)
		
		render json: @routes, status: :ok
	end

	def update  
    @route = Route.find(params[:id])
    
    @route.update(route_params)
    head :no_content
  end

  def route_params
      params.permit(:_json, :done, :id)
  end
end

app/controllers/v1/sessions_controller.rb
class V1::SessionsController < ApplicationController

	def create
		user = User.where(email: params[:email]).first

		if user&.valid_password?(params[:password])
			render json: user.as_json(only: [:id, :email, :authentication_token]), status: :created
		else
			head(:unauthorized)
		end
	end

	def destroy
		current_user&.authentication_token = nil
		if current_user.save
			head :no_content
		else
			head(:unauthorized)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genetic_algorithm_helper.rb
module GeneticAlgorithmHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monitor_helper.rb
module MonitorHelper
end

app/helpers/set_helper.rb
module SetHelper
end

app/views/genetic_algorithm/index.html.erb
<h1>GENETHIC ALGORITHM</h1>
<button>
<div style="text-align: center;">
		<%= link_to("START", {:action => 'index'})%>
	</div>
</button>
<h2>initial distans: <%= @initial_dist %></h2>
<h2>final distans: <%= @final_dist %></h2>
<h2>solution: <%= @solution %></h2>

<p><%= link_to("HOME", {:controller => 'home'})%><p>

app/views/home/index.html.erb
<p>Welcome in managemant couriers systems ! </p>

<h4>If you want to set new route, please click this button: </h4>

<%= link_to("Set route", set_index_path, class: "navbar-brand") %>

<h4>or if you want to monitoring courier, please click this buttons:</h4>

<%= link_to("Monitoring", monitor_index_path, class: "navbar-brand") %>

app/views/monitor/index.html.erb
<h3>Monitoring</h3>

<p>select courier:</p>

<table class="table table-striped">
		<tr class="info">
			<th>id</th>
			<th>email</th>
			<th>admin</th>
			<th>actions</th>
		</tr>
	<% @users.each do |i| %>
		<tr>
			<td><%= i.id %></td>
			<td><%= i.email %></td>
			<td><%= i.admin %></td>
			<td class="actions">
				<%= link_to("monitoring", :class => 'btn btn-xs btn btn-success')%>
				<%= link_to("set-route", :class => 'btn btn-xs btn btn-success')%>
			</td>
		</tr>
	<%end%>	

	</table>

app/views/monitor/view.html.erb
<h3>Monitorin users: <%= @user_to_monit.email %></h3>

<table class="table table-striped">
		<tr class="info">
			<th>id</th>
			<th>lattitude</th>
			<th>longitude</th>
		</tr>
	<% @position_gps.each do |i| %>
		<tr>
			<td><%= i.id %></td>
			<td><%= i.longitude %></td>
			<td><%= i.latitude %></td>
		</tr>
	<%end%>	
</table>

<h4>Trasa: </h4>

<table class="table table-striped">
		<tr class="info">
			<th>id</th>
			<th>city</th>
			<th>done</th>
		</tr>
	<% @users_current_route .each do |i| %>
		<tr>
			<td><%= i.id %></td>
			<td><%= i.city %></td>
			<td><%= i.done %></td>
		</tr>
	<%end%>	
</table>

app/views/set/index.html.erb
<h1>Set#index</h1>
<p>Find me in app/views/set/index.html.erb</p>


<h3>Monitoring</h3>

<p>select courier:</p>

<table class="table table-striped">
		<tr class="info">
			<th>id</th>
			<th>email</th>
			<th>admin</th>
			<th>actions</th>
		</tr>
	<% @users.each do |i| %>
		<tr>
			<td><%= i.id %></td>
			<td><%= i.email %></td>
			<td><%= i.admin %></td>
			<td class="actions">
				<%= link_to("set_new", {:action => 'new', :id => i.id}, :class => 'btn btn-xs btn-success') %>
				<%= link_to("delete", :class => 'btn btn-xs btn btn-success')%>
			</td>
		</tr>
	<%end%>	

	</table>

app/views/set/new.html.erb
<% if current_user.admin == true %>

  <div class="container">

  <form id="courierForm" action="#">
  <label for="userName">Address 1:</label>
  <input id="address" name="city[0]" type="text" class="inputField">
  <label for="userName">Address 2:</label>
  <input id="address" name="city[1]" type="text" class="inputField">
  <label for="userName">Address 3:</label>
  <input id="address" name="city[2]" type="text" class="inputField">
  <label for="userName">Address 4:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 5:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 6:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 7:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 8:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 9:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <label for="userName">Address 10:</label>
  <input id="address" name="userName" type="text" class="inputField">
  <button type="button" class="btn btn-info confirmForms">Confirm forms</button>
</form>

    <button class="btn btn-warning" onclick="getDistanceMatrix()">Get google Distance Matrix</button>
    <button class="btn btn-success" onclick="sentToSidekiq()">GA</button>
    <%= link_to("zapisz", {:action => 'createTour', :id => params[:id]}, :class => 'btn btn-primary')%>
    <div id="right-panel">
      <div id="inputs">
    </div>
    <div>
        <strong>Results</strong>
    </div> 
    <div id="output"></div>
    </div>
    <div id="map"></div>
  </div>
<% else %>
  <div><h2>Zaloguj sie jako admin !</h2></div>
<% end %>

    <script>
      var parseJSON = {
        cities: [],
        distances: []
      }

      $( "form" ).submit(function( event ) {
        var $inputs = $('#courierForm :input');
        var values = [];
        $inputs.each(function() {
          parseJSON.cities.push($(this).val());
        });
        parseJSON.cities.pop();
        console.log( parseJSON.cities );
        event.preventDefault();
      });
            
      function getDistanceMatrix() {

        var bounds = new google.maps.LatLngBounds;
        var markersArray = [];
        var originTable = ['Rudna Mała 307','Rzeszów, Kosynierów 25','Rzeszów, Rymanowska 9','Rzeszow, Maczka 6','Rzeszów, Jana Pawła 2 190','Rzeszów, Sosnowa 5','Rzeszów, Rolnicza 1','Rzeszów, Świętego Rocha 9','Rzeszów, Słowackiego 7','Rzeszów, Szafirowa 13'];
        var destinationIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=D|FF0000|000000';
        var originIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=O|FFFF00|000000';
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 55.53, lng: 9.4},
          zoom: 10
        });
        var geocoder = new google.maps.Geocoder;
        var service = new google.maps.DistanceMatrixService;
        service.getDistanceMatrix({
          origins: originTable,  // zamienic na parseJSON.cities !!!!! 
          destinations: originTable,
          travelMode: 'DRIVING',
          unitSystem: google.maps.UnitSystem.METRIC,
          avoidHighways: false,
          avoidTolls: false
        }, function(response, status) {
          if (status !== 'OK') {
            alert('Error was: ' + status);
          } else {
            var originList = response.originAddresses;
            console.log('originList', originList);
            console.log('response: ', response);
            var destinationList = response.destinationAddresses;
            var outputDiv = document.getElementById('output');
            outputDiv.innerHTML = '';
            deleteMarkers(markersArray);
            // parsowanie JSON do wysylki do sidekiq
            console.log(response);
            parseJSON.cities = originList;
            var count = 0;
            for (var i = 0; i < response.destinationAddresses.length; i++) {
              var results = response.rows[i].elements;
              for (var j = 0; j < response.originAddresses.length; j++) {
                console.log(count);
                  parseJSON.distances[count] = {
                    origin: response.destinationAddresses[i],
                    destination: response.originAddresses[j],
                    distance: results[j].distance.value
                  }
                  console.log(parseJSON.distances[count].origin);
                  console.log(parseJSON.distances[count].destination);
                count++;
              }
              
            }
            console.log('wynikowy json', parseJSON);
            var showGeocodedAddressOnMap = function(asDestination) {
              var icon = asDestination ? destinationIcon : originIcon;
              return function(results, status) {
                if (status === 'OK') {
                  map.fitBounds(bounds.extend(results[0].geometry.location));
                  markersArray.push(new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: icon
                  }));
                } else {
                  //alert('Geocode was not successful due to: ' + status);
                }
              };
            };
            for (var i = 0; i < originList.length; i++) {
              var results = response.rows[i].elements;
              geocoder.geocode({'address': originList[i]},
                  showGeocodedAddressOnMap(false));
              for (var j = 0; j < results.length; j++) {
                geocoder.geocode({'address': destinationList[j]},
                    showGeocodedAddressOnMap(true));
                outputDiv.innerHTML += originList[i] + ' to ' + destinationList[j] +
                    ': ' + results[j].distance.text + ' in ' +
                    results[j].duration.text + '<br>';
              }
            }
          }
        });
      }
      function deleteMarkers(markersArray) {
        for (var i = 0; i < markersArray.length; i++) {
          markersArray[i].setMap(null);
        }
        markersArray = [];
      }
  function sentToSidekiq() {
        
    console.log('json to sent to sidekiq:', parseJSON);
    function output(msg) { console.log(msg) }
    function jobFinished(jobResult) {
      console.log(jobResult);
    }
    function pollJob(jobId, successCallback) {
      function poll() {
        var pollEvery = 3000; // milliseconds
        $.ajax({
          type: "GET",
          url: "/home/fetch/" + jobId, // coupled to your app's routes
          dataType: 'text',
          statusCode: {
            200: function(data) { successCallback(data); },
            202: function(data) { setTimeout(poll, pollEvery); },
            500: function(data) { output('Error!'); }
          }
        });
      };
      poll();
    }
    output('Creating...');
    $.ajax({
      type: "POST",
      url: "/home/create",
      data: parseJSON,
      dataType: 'json',
      success: function(data) {
        output('Job queued, waiting...');
        pollJob(data.jobId, jobFinished);
      }
    });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDviu0iFDidvkkcZ4fLZysw6W8tDuA-Hsg">
    </script>
  </body>
</html>